### ISSUE TITLE
Echo command on windows 10

### ISSUE THREAD

**Issue by arthuro555** [sloria/doitlive#101]
Hello. On windows 10 the echo command (that I use to write files) doesn't work. The programm crashes with the error No such file or directory when I use the record parameter to record the session.

**Comment by PandaWhoCodes** [comment]
Full error
```
ashis@g33k:Desktop $ @echo off
Traceback (most recent call last):
  File "c:\python3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\python3\Scripts\doitlive.exe\__main__.py", line 9, in <module>
  File "c:\python3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "c:\python3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "c:\python3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "c:\python3\lib\site-packages\doitlive\cli.py", line 329, in play
    commentecho=commentecho)
  File "c:\python3\lib\site-packages\doitlive\cli.py", line 189, in run
    magicrun(command, **state)
  File "c:\python3\lib\site-packages\doitlive\keyboard.py", line 131, in magicrun
    extra_commands=extra_commands, test_mode=test_mode)
  File "c:\python3\lib\site-packages\doitlive\keyboard.py", line 119, in run_command
    return subprocess.call([shell, fp.name])
  File "c:\python3\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\python3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\python3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by StephenRoille** [comment]
Hey @arthuro555, I just got the same issue running on Windows 10. If you look at the traceback you can see the error occurs on line **119** in `keyboard.py`:

`File "c:\python3\lib\site-packages\doitlive\keyboard.py", line 119, in run_command
    return subprocess.call([shell, fp.name])`

If you inspect the `shell` variable it seems to be equal to `bin/bash`. Obviously bash is not available out-of-the-box on Windows, but since you are using **GitHub** I assume you have **git** installed on your machine. Apparently, all you need to do is overwrite this `shell` value with your actual `bash.exe` path.

To resolve the issue I imported the `sys` module and added the following condition at the top of the `run_command` function in the `keyboard.py` file,

`import sys`
...
`if sys.platform == "win32":`
`... # use the path to your bash.exe file here`
`... shell = "C:/Program Files/Git/usr/bin/bash.exe"`

After that fix, I was able to use the `doitlive play` and `doitlive record` commands with no issues.
Hope this helps 😉

**Comment by sloria** [comment]
You can set the shell within your session script, at the top of the file:

```sh
#doitlive shell: C:/Program Files/Git/usr/bin/bash.exe
```

**Comment by StephenRoille** [comment]
I tried to set the `--shell` flag directly from the command line but it didn't work (see [documentation examples](https://doitlive.readthedocs.io/en/stable/#examples)),

❌ `doitlive play session.sh --shell "C:\Program Files\Git\usr\bin\bash.exe"`

I also tried to set a `#doitlive shell` comment within the `session.sh` file (as @sloria mentioned) and it worked just fine 👌 (see [documentation configuration](https://doitlive.readthedocs.io/en/stable/#comment-magic-configuration)),

✔ `#doitlive shell: C:/Program Files/Git/usr/bin/bash.exe`

Thanks for the tip.

**Comment by StephenRoille** [comment]
**Correction from my previous.**

The program operates correctly after **removing** the comment
`#doitlive shell: /bin/bash` from the `session.sh` file and issuing the following command,

✔ `doitlive play session.sh --shell "C:\Program Files\Git\usr\bin\bash.exe"`
 
So it seems the file comment `#doitlive shell:` has higher precedence than the `--shell` argument. I think this might be an undesirable effect, most command-line tools are designed to overwrite sensible defaults if command-line arguments are provided. But of course, that is just a personal opinion.

Nonetheless, thank you @sloria for sharing this beautiful and yet amusing package.

**Comment by sloria** [comment]
> So it seems the file comment #doitlive shell: has higher precedence than the --shell argument. 

Woops, that's not intentional. I agree `--shell` should take precedence. PRs welcome to fix that.

Thanks for the kind words!

**Comment by sloria** [comment]
Closing this for now; see workaround above to set your shell on Windows.
