### ISSUE TITLE
Xonsh support?

### ISSUE THREAD

**Issue by deeuu** [sloria/doitlive#119]
Hey,

Great project!

It would be super cool if [xonsh](https://github.com/xonsh/xonsh) scripts were fully supported, e.g.

```python
a = 1
print(a)
echo @(a)
```

Seems not too disimilar from the interactive python console...

Any ideas on this?

Cheers

**Comment by sloria** [comment]
You can configure the shell executable to use when running commands. So you might be able to do something like

```
#doitlive shell: /bin/xonsh
```
