### ISSUE TITLE
function not found in dotilive playbback session

### ISSUE THREAD

**Issue by geoHeil** [sloria/doitlive#128]
When registering a function like:
```
# Recorded with the doitlive recorder
#doitlive shell: /bin/zsh
#doitlive prompt: default

db_set () { echo "$1,$2" >> database }
db_set 123456 '{"name":"Vienna","attractions":["Prater","TU Vienna"]}'

cat database
```

When playing back the session it fails with:
```
/var/folders/lz/vlbj1rj12dzbvbmj16jbp0k80000gn/T/tmp077ulken:3: command not found: db_set
```

but the database file still contains some values:
```
cat database
,
```

How can I get doitlive to recognize the function?

> NOTE originally, the function was written on a multiline string:
```
db_set () {
    echo "$1,$2" >> database
}
```

but this failed to enter the command due to the newline commande.

**Comment by sloria** [comment]
Each line in session gets run in its own process, so functions won't persist across commands. You can work around this using the `#doitlive alias` directive.

```zsh
#doitlive shell: zsh
#doitlive prompt: default

db_set () { echo "$1,$2" >> database }
# doitlive alias: db_set='echo "$1,$2" >> database'
db_set 123456 '{"name":"Vienna","attractions":["Prater","TU Vienna"]}'

cat database
```
