### ISSUE TITLE
get a Warning from python-click 5.1

### ISSUE THREAD

**Issue by pulux** [sloria/doitlive#13]
/usr/lib/python2.7/site-packages/doitlive-2.3.1-py2.7.egg/doitlive.py:598: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/

this fixed it:

```
diff --git a/doitlive.py b/doitlive.py
index 377f102..3aa6408 100755
--- a/doitlive.py
+++ b/doitlive.py
@@ -10,7 +10,7 @@
   :license: MIT, see LICENSE for more details.
 """
 
-from __future__ import unicode_literals
+#from __future__ import unicode_literals
 import datetime as dt
 import functools
 import os
@@ -252,11 +252,11 @@ def get_current_vcs_branch():
 
 
 # Some common symbols used in prompts
-R_ANGLE = TermString('❯')
-R_ANGLE_DOUBLE = TermString('»')
-R_ARROW = TermString('➔')
-DOLLAR = TermString('$')
-PERCENT = TermString('%')
+R_ANGLE = TermString(u'❯')
+R_ANGLE_DOUBLE = TermString(u'»')
+R_ARROW = TermString(u'➔')
+DOLLAR = TermString(u'$')
+PERCENT = TermString(u'%')

```

**Comment by Stefan-Code** [comment]
I just tried your fix, but unfortunately it's a bit more complicated than that. Playing back a sessions works but some unit-tests regarding themes fail. I fixed it [like this](https://github.com/sloria/doitlive/compare/dev...Stefan-Code:features#diff-6ace87c3985e23432db5114d762f8f1eR49) for now, although it's not a very elegant solution.

**Comment by Stefan-Code** [comment]
Fixed this in [my latest pull request](https://github.com/sloria/doitlive/pull/14)
