### ISSUE TITLE
Unable to activate a conda environment during recording

### ISSUE THREAD

**Issue by omry** [sloria/doitlive#147]
I am noticing a few issues that suggests that you are a different shell (and configuration) inside the recording session.
Any idea?

```
(REC) omry@debian:demo $ conda activate hydra-demo

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


(REC) omry@debian:demo $ source activate hydra-demo
/tmp/tmp5d9ws7: line 4: activate: No such file or directory
```

**Comment by sloria** [comment]
I don't have any experience using doitlive with conda, so I can't provide much help here. Hopefully other users can provide assistance.

**Comment by omry** [comment]
How are you creating the shell?
For some reason many things are behaving differently, tab completion, history search with up and down etc.

**Comment by sloria** [comment]
Each command is written to a file then executed within a subprocess: https://github.com/sloria/doitlive/blob/99017d59e6f6610d749b8e0d129681e414e959f9/doitlive/keyboard.py#L104-L131 . 😬

**Comment by omry** [comment]
I see, this explains it.
conda requires some changes to the shell (new functions, aliases etc).
it can't work if the shell does not persist.

Wouldn't it be better to keep a shell open and send keys to it's stdin and read  from it's stdout?

**Comment by sloria** [comment]
I think I had tried that but it didn't work for reasons I've since forgotten...maybe it wasn't feasible to get python mode working. ¯\\_(ツ)_/¯

**Comment by omry** [comment]
oh well.
seems to be working with asciinema, but real time makes things hard.
https://asciinema.org/a/0SSPYKs0h9u5XnmSDln0ET8y7

**Comment by sloria** [comment]
You might be able to fake it by using `#doitlive env` and `#doitlive alias` (https://doitlive.readthedocs.io/en/stable/#comment-magic-configuration) to set the things conda needs. Other than that, I'm afraid I can't provide much other help, so closing. 

Please post here if you get it working.
