### ISSUE TITLE
passing a negative integer to "-s/--speed" causes interesting behavior :)

### ISSUE THREAD

**Issue by mblhaunted** [sloria/doitlive#17]
See subject. 

`[m1001@thallium]:[~/Documents/dev/git/Autobot/vagrant]: doitlive play demo.sh -s -5`
`m1001@thallium:vagrant $ ./get_i` <-- cannot type beyond this bit of command :)

**Comment by sloria** [comment]
Good catch. We should raise an error of a negative value is passed for speed. PRs welcome. =)

**Comment by Stefan-Code** [comment]
It should be enough to pass `type=click.IntRange(1, upper_limit)` to the click option.

**Comment by sloria** [comment]
@Stefan-Code Using `IntRange` worked. Thanks for the suggestion.
