### ISSUE TITLE
Drop support for Python 2

### ISSUE THREAD

**Issue by sloria** [sloria/doitlive#202]
https://gist.github.com/sloria/b4a5fc2281f86a5733af198d609c5ab3

**Comment by cwkang1998** [comment]
I would like to help, may I know how I can contribute?

**Comment by sloria** [comment]
Thanks! Check out the contributing guide for instructions on how to set up locally: https://github.com/sloria/doitlive/blob/dev/CONTRIBUTING.md .

As for this specific task, you can roughly follow my checklist for dropping Python 2: https://gist.github.com/sloria/b4a5fc2281f86a5733af198d609c5ab3 . Adding that to the OP.
