### ISSUE TITLE
Issue with python 3.9 and ipython shell

### ISSUE THREAD

**Issue by lsignac** [sloria/doitlive#211]
Script file example : 

    ```ipython
    print("Hi!")
    ```

When ipython starts : 
~~~
...
from prompt_toolkit.interface import CommandLineInterface, _InterfaceEventLoopCallbacks
ModuleNotFoundError: No module named 'prompt_toolkit.interface'
...
~~~

It seems that `interface` disappeared from `prompt_toolkit` a long time ago

Python 3.9.0 (default, Oct  7 2020, 23:09:01)
prompt-toolkit==3.0.8
doitlive==4.3.0

Everything works well with 

    ```python
    print("Hi")
    ```

**Comment by sloria** [comment]
What version of ipython are you using?

**Comment by lsignac** [comment]
ipython==7.19.0
prompt-toolkit==3.0.10 (has been updated)
Python 3.9.1 (has been updated)

Thx.

**Comment by sloria** [comment]
Oh, you're on ipython 7. doitlive currently only works with 6: https://github.com/sloria/doitlive/issues/91 . So right now you'll either need to downgrade to 6 or use ```python instead.

**Comment by lsignac** [comment]
OK I didn't see that doitlive only worked with ipython6. Thank you for your answer.
