### ISSUE TITLE
Handle Ctrl-L so we don't have to use `clear` all the time

### ISSUE THREAD

**Issue by Kaligule** [sloria/doitlive#217]
In a terminal, Ctrl-L works the same as entering `clear`: It scrolls down until only the current line is visable.

It would be cool if doitlive could handle Ctrl-L the same way, as it is less distracting than an additional command (`clear`) after command that produces much output.

**Comment by sloria** [comment]
This would be convenient. PRs welcome!

**Comment by DvirB10** [comment]
Hi! I've opened a PR at #237 for this issue :)

Couldn't manage to link the PR to this issue :sweat_smile:

**Comment by sloria** [comment]
merged in https://github.com/sloria/doitlive/pull/237
