### ISSUE TITLE
Don't end at the end

### ISSUE THREAD

**Issue by technovangelist** [sloria/doitlive#26]
I wish there was a way to not end automatically at the end of the session. This tool is like magic and seeing `FINISHED SESSION` breaks the illusion when up on stage.

**Comment by PandaWhoCodes** [comment]
You could just comment out this line in your terminal to avoid that message at the end.
https://github.com/sloria/doitlive/blob/c4a9f8e7d255cb32c97d8c8e6e2e1e6609c6e4fc/doitlive/__init__.py#L594

**Comment by sloria** [comment]
I would be open to adding a `--quiet` option that would suppress messages at the beginning and end. PRs welcome! =)

**Comment by PandaWhoCodes** [comment]
You already have a quiet option
https://github.com/sloria/doitlive/blob/c4a9f8e7d255cb32c97d8c8e6e2e1e6609c6e4fc/doitlive/__init__.py#L648
but it just supresses the start-up message not the end message
Submitting a PR for that.

**Comment by sloria** [comment]
Ah, right haha. Thanks!

**Comment by PandaWhoCodes** [comment]
@technovangelist hope this solves your problem

**Comment by technovangelist** [comment]
Thanks

**Comment by sloria** [comment]
This is released in 3.0.3.
