### ISSUE TITLE
The mindset behind doitlive?

### ISSUE THREAD

**Issue by unfa** [sloria/doitlive#28]
Hey!

I stumbled upon this tool, but I don't really know why or when I would want to use it.
I feel like I wouldn't quite feel fine using it, instead of _really_ doing it live.

Could you share the mindset behind this project? I have a hard time understanding it.

As a vocalist I imagine how I'd feel performing a concert with a pre-recorded vocal track (instead of me singing) where the playback is gated with my mic, so it'll trigger the recorded singing, but it's not really me doing it live. It's played back.

Same is here - it's a pre-recorded terminal session that is triggered with my typing. but it's not really me typing what you see on the screen.

What say though?
Maybe you'd want to add a position to your FAQ titled "Isn't this cheating?"

**Comment by Cinderhaze** [comment]
The commands still execute, so it is just the input that is ‘canned’

The audience may not want to (or you don’t have time to) manually type all the commands, but it may be useful for future reference (if it is recorded) to have the full commands shown, instead of just kicking them off in a script

**Comment by sloria** [comment]
A tech talk is unlike a vocal performance in that the audience isn't there to experience the authenticity of your typing. Whether you present with slides, without slides, with doitlive, with a Jupyter notebook, or whatever--the audience is there for the content of your talk. And it doesn't hurt to be entertaining. It *does* hurt if you fumble around with typos.

Try turning up the speed to something ridiculous. Or just tell your audience that you're faking it. These will save time and make the gimmick less of a distraction.

Honestly, I'm still not sure how I'd answer "Isn't this cheating?" Maybe it is, maybe not. For me, this is just a silly project that's fun to write and use.
