### ISSUE TITLE
Support "pasted" text

### ISSUE THREAD

**Issue by ilikebits** [sloria/doitlive#31]
Sometimes I'll be running a demo where paste some text (e.g. a JSON blob or a URL). Is there any way to simulate this with `doitlive`? Typing that text out would be very conspicuous.

**Comment by sloria** [comment]
You could use `pbpaste` (on macOS) or whatever your OS-specific command for pasting is. That said, I wouldn't worry too much about making your session look too real. I've found it better to make it clear that the magic-typing is a gimmick and turn up the speed to something high. This saves the audience's time and makes the gimmick less of a distraction.
