### ISSUE TITLE
How to use with Windows ?

### ISSUE THREAD

**Issue by checkraiser** [sloria/doitlive#4]
I'm using Windows 7. I've tried the session in examples, but it failed. I tried also with Git Bash it failed also. Could you tell me how to test on Windows ?
Thank you.

**Comment by Stefan-Code** [comment]
Also see https://github.com/sloria/doitlive/issues/10 regarding the windows topic. Because it doesn't work, these two issues are now duplicates more or less.

**Comment by sloria** [comment]
The issue in #10 is now fixed in 3.0.1. I can't guarantee full compatibility with Windows, as I don't have a machine to test on. I'm going to close this for now, as this issue is stale.

Feel free to open a new issue if new problems arise.

**Comment by eXigentCoder** [comment]
Hey, thanks for putting together this app, I tried installing on windows 10 with python 3.6.3 (In normal/admin command prompt, powershell and git bash) and got the following error:

```C:\Development
λ python --version
Python 3.6.3

C:\Development
λ pip install doitlive
Collecting doitlive
  Using cached doitlive-3.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\username\AppData\Local\Temp\pip-build-859t1fyr\doitlive\setup.py", line 31, in <module>
        __version__ = find_version('doitlive/__init__.py')
      File "C:\Users\username\AppData\Local\Temp\pip-build-859t1fyr\doitlive\setup.py", line 22, in find_version
        for line in fp:
      File "c:\python36\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5649: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\username\AppData\Local\Temp\pip-build-859t1fyr\doitlive\```

**Comment by sloria** [comment]
@eXigentCoder  The problem is that the file is being opened with the wrong encoding (cp1252 rather than utf-8). I've just pushed up the fix. 

Would you mind testing it out? Clone this repo and cd into it, then run `pip install .` .
