### ISSUE TITLE
Fix documentation for default value of --shell

### ISSUE THREAD

**Issue by sloria** [sloria/doitlive#43]
The default for the `--shell` option uses the `get_default_shell` function to get the user's default shell. The help text is incorrect:

```
doitlive play --help
```

```
Usage: doitlive play [OPTIONS] SESSION_FILE

  Play a session file.

Options:
  -e, --commentecho            Echo non-magic comments.
  -p, --prompt <prompt_theme>  Prompt theme.  [default: default]
  -s, --speed <int>            Typing speed.  [default: 1]
  -S, --shell <shell>          The shell to use.  [default: <function
                               get_default_shell at 0x1033fc6a8>]
  -q, --quiet                  Suppress startup and ending message.
  -h, --help                   Show this message and exit.
```

The `repr` for `get_default_shell` is used. We should find a way to override the docs for the default value so that we can document it to say `[default: $SHELL]`.

**Comment by bisen2** [comment]
I have a pretty hacky workaround in my fork. I essentially just replaced the function call with what it would have done. Can submit a PR if you want, but I am not able to test on Windows or MacOS environments.

**Comment by sloria** [comment]
I think the problem is that we're setting `show_default=True`  on the `--shell` option. We should set that to `False` and document it manually. I'll try this out.

**Comment by sloria** [comment]
That worked!
