### ISSUE TITLE
FR: integrate / merge with demoshell

### ISSUE THREAD

**Issue by aspiers** [sloria/doitlive#48]
https://github.com/dhellmann/demoshell/ is a cool project which IMHO complements doitlive very nicely.  Furthermore, they are both Python, so it would be awesome if they could be integrated or even merged together, to get the best of both worlds.  I filed [a corresponding issue](https://github.com/dhellmann/demoshell/issues/23)  in demoshell's repository.

**Comment by sloria** [comment]
Cool! I hadn't seen demoshell before.

I don't think I'll have time to do this myself, but if you get something working, I'd be glad to review it.

**Comment by sloria** [comment]
Closing this for now. Feel free to re-open if there's still interest.

**Comment by aspiers** [comment]
I just suggested a practical approach to implementing this integration: https://github.com/dhellmann/demoshell/issues/3#issuecomment-442641621
