### ISSUE TITLE
how to source zsh functions

### ISSUE THREAD

**Issue by senior7515** [sloria/doitlive#53]
I have a function in a zsh script. 

i use the `doitlive play session.sh --shell /usr/bin/zsh` 

inside it i source it manually via

```#!/usr/bin/env zsh
   source ~/..../custom_script.zsh
   # call function from script here <<>>
   custom_script_function
```
However all the `commands` in the custom script are not found.

**Comment by sloria** [comment]
Each command in a session runs in an isolated subprocess, so commands from source'd scripts won't be available, unfortunately.
