### ISSUE TITLE
support typing inside vim ?

### ISSUE THREAD

**Issue by iddoeldor** [sloria/doitlive#83]

**Comment by sloria** [comment]
It's a great idea, but I'm not sure how it would work. If anyone wants to take a stab at it, I'd  gladly review and merge a PR.

**Comment by iddoeldor** [comment]
ok, please label with "help needed" &| "enhancement"

**Comment by deeuu** [comment]
@iddoeldor Not entirely sure what you were after, but how about [Posero](https://github.com/alfredodeza/posero.vim/tree/56dd0ef737b70a9e1245ca333cec10390699d7b8)?

[Demo](https://www.youtube.com/watch?v=BtlxLAuWn3A)

**Comment by sloria** [comment]
Posero looks promising for this use case. Thanks @deeuu .

Closing this for now. Will reopen if there's any more discussion needed.
